title: _pixelated_flood
email: yo@yazid.xyz
description: >-
  Personal blog of Yazid Hamdi
baseurl: ""
url: "http://yazid.xyz"
author:
  name: Yazid Hamdi
  picture: /images/profilepic.png
github_username:  yazidhamdi
linkedin_username: yazidhamdi
logo: /images/profilepic.png

# Build settings
remote_theme: "mmistakes/jekyll-theme-basically-basic"
plugins:
  - jekyll-feed